### ISSUE TITLE
Upstream build usage, ARM tests, MySQL issue

### ISSUE THREAD

**Issue by M5oul** [YunoHost-Apps/gogs_ynh_old#44]
Just a new ticket to answer [this comment](https://github.com/YunoHost-Apps/gogs_ynh/issues/43#issuecomment-239770899) and give feedback on testing [upstream build usage package](https://github.com/mbugeia/gogs_ynh_binary).
Also the post has grow too much and went in an other direction.

---

Out of subject, that's great, it seems [next Gogs version will be 0.10.0](https://github.com/gogits/gogs/milestones?state=open).

---

I think It's great to use upstream build.
I also do that with most of packages I maintain: [Duniter](https://github.com/duniter/duniter_ynh), [PluXml](https://github.com/YunoHost-Apps/pluxml_ynh), [Sonerezh](https://github.com/YunoHost-Apps/sonerezh_ynh), and [Cesium](https://github.com/duniter/cesium_ynh).

---

Thanks for the package.
I tested it on my ARM board.
I found bugs corrected on [this pull request](https://github.com/mbugeia/gogs_ynh_binary/pull/1).
The big issue is MySQL:

```
Warning: Created symlink from /etc/systemd/system/multi-user.target.wants/gogs.service to /etc/systemd/system/gogs.service.
+ sudo systemctl start gogs.service
++ ynh_mysql_connect_as gogs 2xP0AgVgpWdxZEIi2kpM7zaP gogs
++ mysql -u gogs --password=2xP0AgVgpWdxZEIi2kpM7zaP -B gogs
+ sleep 2
++ ynh_mysql_connect_as gogs 2xP0AgVgpWdxZEIi2kpM7zaP gogs
++ mysql -u gogs --password=2xP0AgVgpWdxZEIi2kpM7zaP -B gogs
+ sleep 2
(…)
(…) # I removed many of them.
(…)
++ ynh_mysql_connect_as gogs 2xP0AgVgpWdxZEIi2kpM7zaP gogs
++ mysql -u gogs --password=2xP0AgVgpWdxZEIi2kpM7zaP -B gogs
+ sleep 2
++ ynh_mysql_connect_as gogs 2xP0AgVgpWdxZEIi2kpM7zaP gogs
++ mysql -u gogs --password=2xP0AgVgpWdxZEIi2kpM7zaP -B gogs
+ sleep 2
^CProcess Process-4:
Traceback (most recent call last):
```

I had to kill it. May it's linked to the [issue encountered with @stevenroose package](https://github.com/YunoHost-Apps/gogs_ynh/issues/40#issuecomment-234788056).

Database was well created.

**Comment by mbugeia** [comment]
Hi,
thanks for the feedback and the PR. Are you sure the database was correctly created ? 
With the tar command I'm using "--strip-components 1" which extract gogs binary at the place that the systemd script expect (/opt/gogs/gogs) . With your PR it's extracted to /opt/gogs/gogs/gogs, that can explain why gogs was probably not started and why the mysql thing happen.
Unfortunatly there is no such argument with unzip but that can be corrected (http://superuser.com/questions/518347/equivalent-to-tars-strip-components-1-in-unzip).

**Comment by mbugeia** [comment]
@M5oul I've pushed a fix based on your PR which use zip and a temp directory to extract gogs to avoid the issue.

**Comment by M5oul** [comment]
Wow, thanks.
I tested this version.
I still have the MySQL issue.
I am sure db was well created:

``` bash
+ DESTDIR=/opt/gogs
+ [[ -d /opt/gogs ]]
++ ynh_string_random
++ tr -c -d '[A-Za-z0-9]'
++ sed -n 's/\(.\{24\}\).*/\1/p'
++ dd if=/dev/urandom bs=1 count=200
+ dbpass=
++ ynh_string_random
++ tr -c -d '[A-Za-z0-9]'
++ sed -n 's/\(.\{24\}\).*/\1/p'
++ dd if=/dev/urandom bs=1 count=200
+ key=
+ ynh_mysql_create_db gogs gogs ''
+ db=gogs
+ sql='CREATE DATABASE gogs;'
+ [[ 3 -gt 1 ]]
+ sql+=' GRANT ALL PRIVILEGES ON gogs.* TO '\''gogs'\''@'\''localhost'\'''
+ [[ -n  ]]
+ sql+=' IDENTIFIED BY '\'''\'''
+ sql+=' WITH GRANT OPTION;'
+ ynh_mysql_execute_as_root 'CREATE DATABASE gogs; GRANT ALL PRIVILEGES ON gogs.* TO '\''gogs'\''@'\''localhost'\'' IDENTIFIED BY '\'''\'' WITH GRANT OPTION;'
++ sudo cat /etc/yunohost/mysql
+ ynh_mysql_connect_as root  ''
+ mysql -u root --password= -B ''
+ ynh_app_setting_set gogs mysqlpwd ''
```

It seems the issue come from the fact my previous gogs install which broke (I don't know exactly why) let some relics on db.

I should reinstall my YunoHost instance or fix that MySQL db.

**Comment by mbugeia** [comment]
Sorry when I asked about the database created it was about the gogs's tables being created. It's normal to have a bunch of "sleep 2", it's to let gogs the time to create all the tables. It takes less than 10s on my VPS but I assume on an arm board it can be longer.  Did you let it wait some time before killling it ?
Another check is when the sleep happen, does the service gogs started (systemctl status gogs.service) ?

I don't think a previous install of gogs package can broke this.

**Comment by M5oul** [comment]
During all sleeps, even 11:45 min later:

``` mysql
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| gogs               |
+--------------------+
2 rows in set (0.01 sec)

mysql> show databases;^CCtrl-C -- exit!
Aborted
root@cubieboard2:~# mysql -u gogs '--password='
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 291
Server version: 5.5.50-0+deb8u1 (Debian)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use gogs
Database changed
mysql> show tables;
Empty set (0.00 sec)

mysql> 
```

I let for 11:45 minutes, and it still didn't works.

**Comment by M5oul** [comment]
That's strange, because start it and see that it's running with `status`, then a bit later, it's down:

``` bash
systemctl status gogs.service
● gogs.service - Gogs (Go Git Service)
   Loaded: loaded (/etc/systemd/system/gogs.service; enabled)
   Active: failed (Result: start-limit) since Tue 2016-08-30 23:17:43 CEST; 4s ago
  Process: 3871 ExecStart=/opt/gogs/gogs web (code=exited, status=1/FAILURE)
 Main PID: 3871 (code=exited, status=1/FAILURE)

Aug 30 23:17:43 cubieboard2 systemd[1]: gogs.service: main process exited, code=exited, status=1/FAILURE
Aug 30 23:17:43 cubieboard2 systemd[1]: Unit gogs.service entered failed state.
Aug 30 23:17:43 cubieboard2 systemd[1]: gogs.service holdoff time over, scheduling restart.
Aug 30 23:17:43 cubieboard2 systemd[1]: Stopping Gogs (Go Git Service)...
Aug 30 23:17:43 cubieboard2 systemd[1]: Starting Gogs (Go Git Service)...
Aug 30 23:17:43 cubieboard2 systemd[1]: gogs.service start request repeated too quickly, refusing to start.
Aug 30 23:17:43 cubieboard2 systemd[1]: Failed to start Gogs (Go Git Service).
Aug 30 23:17:43 cubieboard2 systemd[1]: Unit gogs.service entered failed state.
```

**Comment by mbugeia** [comment]
Can you check the logs in /var/log/gogs to see why it failed ? Check before killing the yunohost install or they will be deleted by the remove script.

**Comment by M5oul** [comment]
Finally,
there was a permission issue on `/home` repository.
Thanks for the help.
